### ISSUE TITLE
rendering

### ISSUE THREAD

**Issue by SunshineJunFu** [briandicky/edge_rendering#2]
I notice this prototype could work with Oculus in your paper. And could you share some ideas about how to render image in FOV to Oculus？ Thanks a lot:-)

**Comment by briandicky** [comment]
Hi @fujunustc,

I am not sure which paper you mentioned.
Actually, this work is still under construction. At this moment, it cannot render the AR/VR content into HMDs (e.g., Oculus DK2) directly.

If you want to render AR/VR content to HMDs, [this](http://www.osvr.org/) might be helpful.

Thanks,
WC

**Comment by SunshineJunFu** [comment]
Thanks for reply:-)
